microservice-chart: &microservice-chart
  namespace: "fdr"
  image:
    repository: ghcr.io/pagopa/pagopa-fdr-json-to-xml
    tag: "0.2.9"
    pullPolicy: Always
  livenessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  readinessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  deployment:
    create: true
    replicas: 1 # (default) same as HPA minReplica
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 12345 #jmx-exporter
    - 8080
  service:
    type: ClusterIP
    ports:
      - 8080
      - 12345 #jmx-exporter
  ingress: &ingress
    create: true
    host: "weuuat.fdr.internal.uat.platform.pagopa.it"
    path: /pagopa-fdr-json-to-xml/(.*)
    servicePort: 8080
  serviceAccount:
    name: "fdr-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources: &resources
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "768Mi"
      cpu: "0.40"
  autoscaling: &autoscaling
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig: &envConfig
    APP_ENVIRONMENT: "uat"
    #    JAVA_OPTS: "-XX:MaxHeapSize=256m -XX:MinHeapSize=64m"
    WEBSITE_SITE_NAME: "pagopafdrjsontoxml" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    FDR_FASE1_BASE_URL: "https://api.uat.platform.pagopa.it/fdr-nodo/service-internal/v1"
    BLOB_STORAGE_FDR3_CONTAINER: "fdr3-flows"
    ERROR_TABLE_NAME: "fdr3conversionerror"
    ASPNETCORE_URLS: "http://*:8080"
    FUNCTIONS_SECRETS_PATH: "/tmp/secrets"
    AzureFunctionsWebHost__hostid: "fdr-json-to-xml"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-connection-string"
    FDR_FASE1_API_KEY: "fdr-internal-product-subscription-key"
    FDR_SA_CONNECTION_STRING: "fdr-sa-connection-string"
    TABLE_STORAGE_CONN_STRING: "fdr-sa-connection-string"
    AzureWebJobsStorage: "fdr-sa-connection-string"
  keyvault:
    name: "pagopa-u-fdr-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo
                operator: In
                values:
                  - "true"
  canaryDelivery:
    create: false
# ALL TRIGGER FUNCTION
functions:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
  autoscaling:
    !!merge <<: *autoscaling
  envConfig:
    !!merge <<: *envConfig
    WEBSITE_SITE_NAME: "pagopafdrjsontoxml" # required to show cloud role name in application insights
    AzureFunctionsWebHost__hostid: "fdr-json-to-xml-functions"
    AzureFunctionsJobHost__functions__0: "Info"
    AzureFunctionsJobHost__functions__1: "BlobEventProcessor"
    AzureFunctionsJobHost__functions__2: "ErrorRetryFunction"
    AzureFunctionsJobHost__functions__3: "ErrorRetryAllFunction"
